version: "3.8"

services:
  nextjs:
    image: ghcr.io/jmoren2/simple-ai-macro-tracker:latest
    env_file:
      - .env
    container_name: simple-ai-macro-tracker
    restart: always
    ports:
      - "4000:3000"
