version: "3.8"

services:
  nextjs:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-ai-macro-tracker
    restart: always
    ports:
      - "4000:3000"
